/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Register$Params as Register$Params } from './fn/auth-controller/register';
export { register as register } from './fn/auth-controller/register';
export type { Login$Params as Login$Params } from './fn/auth-controller/login';
export { login as login } from './fn/auth-controller/login';
